version: 4.16.3

services:

  nginx:
    container_name: nginx
    image: nginx:1.24
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/static:/opt/jirarush/resources/static:ro
    depends_on:
      - localhost
    restart: always

  localhost:
    env_file:
      - docker-env.list
    image: project-final
    container_name: jirarush
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DB: ${SPRING_DATASOURCE_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    env_file:
      - docker-env.list
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U jira -d jira'"]
      interval: 2s
      timeout: 30s
      retries: 10
    restart: always
